### ISSUE TITLE
tfidf

### ISSUE THREAD

**Issue by mrchypark** [mrchypark/textR#6]
![image](https://user-images.githubusercontent.com/6179259/47669547-78c9f180-dbee-11e8-85e8-e01cb4cbe46d.png)

**Comment by EmilHvitfeldt** [comment]
Hello Park!

How this you create this nice graphic?

**Comment by mrchypark** [comment]
it's from <https://www.bloter.net/archives/264262>!

**Comment by mrchypark** [comment]
@EmilHvitfeldt oh... anyway, may I translate your post in korean? <https://www.hvitfeldt.me/2018/09/usethis-workflow-for-package-development/>

**Comment by EmilHvitfeldt** [comment]
Thank you! 

>  may I translate your post in korean?
Be my guest! Please ask if you have any questions. And send the result when you are done so I can help spread the word!
